# Generated by Django 3.1.1 on 2020-09-18 06:13

import app_shortener_url.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=app_shortener_url.models.get_random_key, unique=True, verbose_name='Укороченный URL')),
                ('original_url', models.URLField(max_length=500, verbose_name='Исходная URL ссылка')),
                ('ip_client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_shortener_url.clientmodel', verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ('-id',),
            },
        ),
    ]
